name: Haskell CI
on: [push]
variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
cache:
  paths:
    - .stack-work/
    - .stack-root/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        enable-stack: true
        stack-version: 'latest'
    - name: Build
      run: stack init
    - name: Run tests
      run: stack test
